Added test for CVS repository sync problem.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -10,9 +10,40 @@ AC_CONFIG_AUX_DIR(cfg)
 
 sim_ac_cvs_syncproblem=false;
 
-if test "x$sim_ac_cvs_syncproblem" = "xtrue"; then
-  exit
+sim_ac_macro_dir=${srcdir}/cfg/m4
+
+if test ! -d $sim_ac_macro_dir; then
+  if test "x${with_auto_cvs_update+set}" = "xset"; then
+    echo "Trying to honor the --with-auto-cvs-update option."
+    sim_ac_save_cwd="`pwd`"
+    cd ${srcdir}
+    if test -d cfg/m4 -o ! -f ./CVS/Entries; then
+      AC_MSG_ERROR([something failed horribly - can't do auto-cvs-update])
+    fi
+    cvs co SoGtkMacros
+    cd ${sim_ac_save_cwd}
+    echo "Done.  Proceeding..."
+  fi
 fi
+
+if test ! -d $sim_ac_macro_dir; then
+  cat <<EOF
+
+  You appear to have an old setup of the SoGtk source repository.
+  Parts of it have changed structurally, and you need to do the
+  following in the SoGtk source directory:
+
+    $ rm -rf conf-macros
+    $ cvs co SoGtkMacros
+
+  You can also run configure with the option --with-auto-cvs-update
+  to allow the configure script to try to take care of this.  This
+  option is a bit experimental - use at your own risk.
+EOF
+  sim_ac_cvs_syncproblem=true
+fi
+
+$sim_ac_cvs_syncproblem && echo "" && echo "Aborting..." && exit 1
 
 # **************************************************************************
 # Locate C++ compiler and set C++ as the default compiler to run in tests.
